kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-apache
spec:
  storageClassName: nfs-apache
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.18.197.109
    path: "/mnt/nfs_share/apache"
    readOnly: false
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-nginx
spec:
  storageClassName: nfs-nginx
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.18.197.109
    path: "/mnt/nfs_share/nginx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-apache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-apache"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-nginx"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nfs
      mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs-pvc-nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache-pod
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nfs
      mountPath: "/usr/local/apache2/htdocs"
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs-pvc-apache
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  labels:
    app: apache-pod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: portal
    http:
      paths:
      - path: /apache
        pathType: Prefix
        backend:
          service:
            name: apache-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: nginx-pod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: portal
      http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
