---
# Curso Online de Cloud Computing con Amazon Web Services
# Provisions and configures a set of VM instances from EC2
# German Molto - @gmolto - September 2014
#
# Run as:
# ansible-playbook -i /opt/cursoaws/ansible/local-inventory  --private-key $HOME/alucloud$ID-priv.pem --extra-vars "id=$ID" /opt/cursoaws/ansible/ansible-provision-ec2.yml
#
#
# ami-3251905a (Ubuntu 14.04 LTS)

#####################
#
#  PROVISION VMs
#
#####################
- name: Provision VMs
  hosts: all
  connection: local
  tags:
    - provision

  vars:
      instance_type: t2.micro
      image: ami-7dce6507 #Ubuntu 14.04 HVM
      subnet_id: subnet-2bfb6c4f #subnet-default-1a-public

  tasks:
    - name: Provisioning EC2 instance(s) (This might take a while ... DO NOT INTERRUPT.)
      local_action: ec2
           keypair="alucloud{{ id }}-keypair"
           group="gs-aws-{{ id }}"
           instance_type={{ instance_type }}
           image={{ image }}
           wait=true
           count=1
           vpc_subnet_id={{subnet_id}}
           region="us-east-1"
           instance_tags='ansible=alucloud{{ id }}'
      register: ec2vms


    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: "{{ ec2vms.instances }}"

    - name: Waiting for the new instance(s) to be ready (This might take a while ... DO NOT INTERRUPT.)
      local_action: wait_for
         host={{item.public_dns_name}} port=22 delay=30 timeout=450 state=started
      with_items: "{{ ec2vms.instances }}"

    - name: Showing your instance(s) information
      debug: msg="Provisioned instance for Ansible {{ item.id }} --> {{ item.public_dns_name }}"
      with_items: "{{ ec2vms.instances }}"


#####################
#
#  CONFIGURE VMs
#
#####################
- name: Configure VM(s)
  hosts: ec2hosts
 # hosts: tag_ansible_alucloud00
  become: yes
  tags:
    - configuration
  pre_tasks:
    - name: Wait for cloud-init to finish
      wait_for: >
        path=/var/log/cloud-init.log
        timeout=15
        search_regex="final-message"

  tasks:
    - name: Install Apache Web Services with PHP support
      apt: name=apache2 update_cache=yes state=present
    - apt: name=php5 state=present
    - name: Retrieve Web Application from S3 bucket
      get_url: url=https://s3.amazonaws.com/cursoscloudupv/cloudformation/cellar-webapp-mem.tgz dest=/tmp validate_certs=no owner=ubuntu group=ubuntu
    - name: Unpacking Web Application
      unarchive: src="/tmp/cellar-webapp-mem.tgz" dest="/var/www/html" copy=no
