kind: PersistentVolume
apiVersion: v1
metadata:
    name: html-stor
    labels:
        type: local
spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Recycle
    capacity:
        storage: 32M
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /tmp/k8s/data
