kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: html-pvc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 16M
