apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-subdir
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    readOnly: False
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  resources:
    requests:
      storage: "128Mi"
  storageClassName: nfs-subdir
  accessModes:
    - ReadWriteMany
    
